menu:
  主页: /
  归档: /archives

logo: BNGH

more:
  Kanban管理: https://42.gaoryrt.com/kanban
  GitHub: https://github.com/gaoryrt/
  rss: /rss2.xml
  微博: http://weibo.com/R1T1AN
  友链: /links.html
  关于我: /CV

about:
  title: Theme Pln
  link: https://github.com/gaoryrt/hexo-theme-pln

show_toc_bool: true

disqus_shortname: gaoryrt

excerpt_num: 125

footer_info: © Gaoryrt 2015-2019

search:
  path: search.xml
  field: all